import { CatalogueItem } from "@/types/commonTypes";

export const menuCatalogue: CatalogueItem[] = [
  {
    category: "Produits",
    items: [
      { title: "Bandana", href: "/catalogue/bandana" },
      { title: "Bandeau", href: "/catalogue/bandeau" },
      { title: "Béret", href: "/catalogue/beret" },
      { title: "Bermuda/Short", href: "/catalogue/bermuda/short" },
      { title: "Bermuda/Short", href: "/catalogue/bermuda/short" },
      { title: "Blouse de travail", href: "/catalogue/blouse-de-travail" },
      { title: "Bob", href: "/catalogue/bob" },
      { title: "Body", href: "/catalogue/body" },
      { title: "Bodywarmer", href: "/catalogue/bodywarmer" },
      { title: "Bonnet", href: "/catalogue/bonnet" },
      { title: "Cagoule", href: "/catalogue/cagoule" },
      { title: "Calot", href: "/catalogue/calot" },
      { title: "Casque", href: "/catalogue/casque" },
      { title: "Casquette", href: "/catalogue/casquette" },
      { title: "Chapeau Bandana", href: "/catalogue/chapeau-bandana" },
      { title: "Chapeau et accessoires", href: "/catalogue/chapeau-et-accessoires" },
      { title: "Chasuble", href: "/catalogue/chasuble" },
      { title: "Chemise/Surchemise", href: "/catalogue/chemise/surchemise" },
      { title: "Chemisier/Blouse", href: "/catalogue/chemisier/blouse" },
      { title: "Combinaison", href: "/catalogue/combinaison" },
      { title: "Débardeur", href: "/catalogue/debardeur" },
      { title: "Écharpe / Étole / Tour de cou", href: "/catalogue/echarpe-/-etole-/-tour-de-cou" },
      { title: "Gants", href: "/catalogue/gants" },
      { title: "Gilet", href: "/catalogue/gilet" },
      { title: "Jean", href: "/catalogue/jean" },
      { title: "Jupe", href: "/catalogue/jupe" },
      { title: "Maillot de bain", href: "/catalogue/maillot-de-bain" },
      { title: "Maillot de sport", href: "/catalogue/maillot-de-sport" },
      { title: "Pantalon/Pantacourt", href: "/catalogue/pantalon/pantacourt" },
      { title: "Polo", href: "/catalogue/polo" },
      { title: "Poncho", href: "/catalogue/poncho" },
      { title: "Pullover/Cardigan", href: "/catalogue/pullover/cardigan" },
      { title: "Robe", href: "/catalogue/robe" },
      { title: "Salopette", href: "/catalogue/salopette" },
      { title: "Sweat", href: "/catalogue/sweat" },
      { title: "Tablier", href: "/catalogue/tablier" },
      { title: "Tablier", href: "/catalogue/tablier" },
      { title: "TShirt", href: "/catalogue/tshirt" },
      { title: "Tunique", href: "/catalogue/tunique" },
      { title: "Tunique", href: "/catalogue/tunique" },
      { title: "Veste", href: "/catalogue/veste" },
    ],
  },
  {
    category: "Marques",
    items: [
      { title: "B&C", href: "/marques/bc" },
      { title: "Beechfield", href: "/marques/beechfield" },
      { title: "Fruit of the Loom", href: "/marques/fruit-of-the-loom" },
      { title: "Gildan", href: "/marques/gildan" },
      { title: "Kariban", href: "/marques/kariban" },
      { title: "Russell", href: "/marques/russell" },
    ],
  },
];
